"""Paper-traceable implementation of non-uniform k-connectivity for UWSNs."""

from .environment import (
    AcousticEnergyEnvironment,
    ConnectivityPartition,
    Deployment,
    EnvironmentData,
    InterferenceEnvironment,
    NetworkEnvironment,
    absorption_coefficient_db_per_km,
    build_acoustic_energy_environment,
    build_directed_arcs,
    build_environment,
    build_explicit_connectivity_partition,
    build_interference_environment,
    build_network_environment,
    build_paper_network_environment,
    build_seeded_connectivity_partition,
    frequency_component,
    generate_uniform_deployment,
    minimum_link_transmission_energy_j_per_bit,
    pairwise_distances,
    power_level_energies_j_per_bit,
    transmission_energy_j_per_bit,
    transmission_loss,
)
from .model import ModelVars, build_model
from .params import (
    AcousticParameters,
    ExperimentParameters,
    NetworkParameters,
    PaperParameters,
    PowerLevelTable,
)

__all__ = [
    "AcousticParameters",
    "AcousticEnergyEnvironment",
    "ConnectivityPartition",
    "Deployment",
    "EnvironmentData",
    "InterferenceEnvironment",
    "ModelVars",
    "ExperimentParameters",
    "NetworkParameters",
    "NetworkEnvironment",
    "PaperParameters",
    "PowerLevelTable",
    "absorption_coefficient_db_per_km",
    "build_acoustic_energy_environment",
    "build_directed_arcs",
    "build_environment",
    "build_explicit_connectivity_partition",
    "build_interference_environment",
    "build_model",
    "build_network_environment",
    "build_paper_network_environment",
    "build_seeded_connectivity_partition",
    "frequency_component",
    "generate_uniform_deployment",
    "minimum_link_transmission_energy_j_per_bit",
    "pairwise_distances",
    "power_level_energies_j_per_bit",
    "transmission_energy_j_per_bit",
    "transmission_loss",
]
