"""PuLP formulation of the Tantur et al. (2025) MILP, Eqs. (6)–(25)."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType

import pulp

from .environment import EnvironmentData

FlowKey = tuple[int, int, int, int]
PathKey = tuple[int, int]


"""Typed handles for all decision variables defined in Section III-C."""
@dataclass(frozen=True, slots=True)
class ModelVars :
    # Keys are (source k, path l, transmitter i, receiver j).
    data_flow    : Mapping[FlowKey, pulp.LpVariable]
    control_flow : Mapping[FlowKey, pulp.LpVariable]
    arc_used     : Mapping[FlowKey, pulp.LpVariable]

    # Keys are (source k, path l).
    path_packets            : Mapping[PathKey, pulp.LpVariable]
    maximum_sensor_energy   : pulp.LpVariable

    def __post_init__(self) -> None :
        object.__setattr__(
            self,
            "data_flow",
            MappingProxyType(dict(self.data_flow)),
        )
        object.__setattr__(
            self,
            "control_flow",
            MappingProxyType(dict(self.control_flow)),
        )
        object.__setattr__(
            self,
            "arc_used",
            MappingProxyType(dict(self.arc_used)),
        )
        object.__setattr__(
            self,
            "path_packets",
            MappingProxyType(dict(self.path_packets)),
        )


"""
    Packets generated by source k flows over path l
    from transmitter i to receiver j
"""
def _flow_variable_name(
    symbol      : str,
    source      : int,
    path        : int,
    transmitter : int,
    receiver    : int,
) -> str :
    return f"{symbol}_k{source}_l{path}_i{transmitter}_j{receiver}"


"""
    Create variables, domains, and Objective (6).

    Paper: Section III-C, Objective (6), and Constraints (23)–(25).

    Path indices remain one-based to match ``l in {1,...,N_l}`` in the paper.
    Node indices remain zero-based according to the environment convention.
"""
def build_model(env: EnvironmentData) -> tuple[pulp.LpProblem, ModelVars] :
    problem = pulp.LpProblem(
        name    = "tantur_2025_non_uniform_k_connectivity",
        sense   = pulp.LpMinimize,
    )
    sensors = env.network.sensors
    arcs    = env.network.arcs
    paths   = tuple(range(1, env.paper.network.maximum_paths + 1))

    flow_keys = tuple(
        (source, path, transmitter, receiver)
        for source in sensors
        for path in paths
        for transmitter, receiver in arcs
    )
    path_keys = tuple((source, path) for source in sensors for path in paths)

    # Paper: Section III-C and Constraint (23), f^kl_ij >= 0 integer.
    data_flow = {
        key : problem.add_variable(
            _flow_variable_name("f", *key),
            lowBound = 0,
            cat      = pulp.LpInteger,
        )
        for key in flow_keys
    }

    # Paper: Section III-C and Constraint (23), g^kl_ij >= 0 integer.
    control_flow = {
        key : problem.add_variable(
            _flow_variable_name("g", *key),
            lowBound = 0,
            cat      = pulp.LpInteger,
        )
        for key in flow_keys
    }

    # Paper: Section III-C and Constraint (24), h^kl_ij is binary.
    arc_used = {
        key : problem.add_variable(
            _flow_variable_name("h", *key),
            cat = pulp.LpBinary,
        )
        for key in flow_keys
    }

    # Paper: Section III-C and Constraint (25), p^l_k >= 0 integer.
    path_packets = {
        key : problem.add_variable(
            f"p_k{key[0]}_l{key[1]}",
            lowBound = 0,
            cat      = pulp.LpInteger,
        )
        for key in path_keys
    }

    # Paper: Section III-C, epsilon is the most energy-consuming sensor's
    # total energy. A non-negative continuous variable is sufficient.
    maximum_sensor_energy = problem.add_variable(
        "epsilon",
        lowBound = 0,
        cat      = pulp.LpContinuous,
    )

    variables = ModelVars(
        data_flow               = data_flow,
        control_flow            = control_flow,
        arc_used                = arc_used,
        path_packets            = path_packets,
        maximum_sensor_energy   = maximum_sensor_energy,
    )

    # Paper: Section III-C, Objective (6), minimize epsilon.
    problem += maximum_sensor_energy, "objective_06_minimize_epsilon"

    _add_constraint_07_flow_conservation(problem, variables, env)
    _add_constraint_08_generated_packets(problem, variables, env)
    _add_constraint_09_no_source_reentry(problem, variables, env)
    _add_constraints_10_11_flow_use_coupling(problem, variables, env)
    _add_constraint_12_single_next_hop(problem, variables, env)

    _add_constraint_13_link_disjointness(problem, variables, env)
    _add_constraint_14_monotone_path_index(problem, variables, env)
    _add_constraints_15_16_phantom_flow(problem, variables, env)
    _add_constraints_19_20_node_disjointness(problem, variables, env)

    _add_constraint_17_control_flow(problem, variables, env)
    _add_constraint_18_non_uniform_connectivity(problem, variables, env)

    _add_constraint_21_energy(problem, variables, env)
    _add_constraint_22_bandwidth(problem, variables, env)

    return problem, variables


"""Number of paths there can be"""
def _paths(env: EnvironmentData) -> range :
    return range(1, env.paper.network.maximum_paths + 1)


"""Egress arcs of the given node"""
def _outgoing_arcs(env: EnvironmentData, node: int) -> tuple[tuple[int, int], ...] :
    return tuple(arc for arc in env.network.arcs if arc[0] == node)


"""Ingress arcs of the given node"""
def _incoming_arcs(env: EnvironmentData, node: int) -> tuple[tuple[int, int], ...] :
    return tuple(arc for arc in env.network.arcs if arc[1] == node)


"""
    Paper: Section III-C, Constraint (7)

    Packets assigned to a path must form a continuous route from source to BS.
"""
def _add_constraint_07_flow_conservation(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    for node in env.network.nodes :
        outgoing = _outgoing_arcs(env, node)
        incoming = _incoming_arcs(env, node)

        for source in env.network.sensors :
            for path in _paths(env) :
                balance = pulp.lpSum(
                    variables.data_flow[(source, path, *arc)] for arc in outgoing
                ) - pulp.lpSum(
                    variables.data_flow[(source, path, *arc)] for arc in incoming
                )
                if node == source :
                    right_hand_side = variables.path_packets[(source, path)]
                elif node == env.network.bs_index :
                    right_hand_side = -variables.path_packets[(source, path)]
                else:
                    right_hand_side = 0

                problem += (
                    balance == right_hand_side,
                    f"c07_flow_i{node}_k{source}_l{path}",
                )


"""
    Paper: Section III-C, Constraint (8)
    
    Every sensor must deliver its full data volume.
"""
def _add_constraint_08_generated_packets(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    generated_packets = (
        env.paper.network.packets_per_sensor_per_round
        * env.paper.network.number_of_rounds
    )

    for source in env.network.sensors :
        problem += (
            pulp.lpSum(variables.path_packets[(source, path)] for path in _paths(env))
            == generated_packets,
            f"c08_generated_k{source}",
        )


"""
    Paper: Section III-C, Constraint (9).

    Prevents cycles that return to the source and waste energy without helping delivery.
"""
def _add_constraint_09_no_source_reentry(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    sensor_set = set(env.network.sensors)
    for source in env.network.sensors :
        incoming_from_sensors = tuple(
            arc for arc in _incoming_arcs(env, source) if arc[0] in sensor_set
        )

        problem += (
            pulp.lpSum(
                variables.data_flow[(source, path, *arc)]
                for path in _paths(env)
                for arc in incoming_from_sensors
            )
            == 0,
            f"c09_no_reentry_k{source}",
        )


"""
    Paper: Section III-C, Constraints (10)–(11).
    
    h is the structural “this link is on this path” indicator 
    used by disjointness and connectivity constraints.
"""
def _add_constraints_10_11_flow_use_coupling(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    maximum_source_packets = (
        env.paper.network.packets_per_sensor_per_round
        * env.paper.network.number_of_rounds
    )

    for key, flow in variables.data_flow.items() :
        source, path, transmitter, receiver = key
        used                                = variables.arc_used[key]
        suffix                              = f"k{source}_l{path}_i{transmitter}_j{receiver}"

        problem += (flow <= maximum_source_packets * used, f"c10_flow_upper_{suffix}")

        problem += (used <= flow, f"c11_flow_lower_{suffix}")


"""
    Paper: Section III-C, Constraint (12).
    
    Each path slot must be a simple non-branching route, not a tree.
"""
def _add_constraint_12_single_next_hop(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    for node in env.network.sensors :
        outgoing = _outgoing_arcs(env, node)

        for source in env.network.sensors:
            for path in _paths(env) :
                problem += (
                    pulp.lpSum(
                        variables.arc_used[(source, path, *arc)] for arc in outgoing
                    )
                    <= 1,
                    f"c12_single_next_i{node}_k{source}_l{path}",
                )


"""
    Paper: Section III-C, Constraint (13).
    
    For a fixed source k and directed arc (i,j), 
    that arc may be used on at most one path slot.
"""
def _add_constraint_13_link_disjointness(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    for source in env.network.sensors :
        for transmitter, receiver in env.network.arcs :
            problem += (
                pulp.lpSum(
                    variables.arc_used[(source, path, transmitter, receiver)]
                    for path in _paths(env)
                )
                <= 1,
                f"c13_link_disjoint_k{source}_i{transmitter}_j{receiver}",
            )


"""
    Paper: Section III-C, Constraint (14).
    
    Among path slots that carry traffic into the BS, 
    lower indices are filled before higher ones: 
    inflow on path l+1 ≤ inflow on path l.
"""
def _add_constraint_14_monotone_path_index(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    incoming_to_bs = _incoming_arcs(env, env.network.bs_index)
    last_path      = env.paper.network.maximum_paths

    for source in env.network.sensors :
        for path in range(1, last_path) :
            next_path_ingress = pulp.lpSum(
                variables.data_flow[(source, path + 1, *arc)] for arc in incoming_to_bs
            )
            current_path_ingress = pulp.lpSum(
                variables.data_flow[(source, path, *arc)] for arc in incoming_to_bs
            )

            problem += (
                next_path_ingress <= current_path_ingress,
                f"c14_path_order_k{source}_l{path}",
            )


"""
    Paper: Section III-C, Constraints (15)–(16).
    
    f an arc is used on path (k,l) (h=1), 
    then the flow on that arc must equal the path packet count p^l_k. 
    If unused (h=0), the big-M terms deactivate the equalities so they do not bind.
"""
def _add_constraints_15_16_phantom_flow(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    big_m = env.paper.network.big_m
    for key, flow in variables.data_flow.items() :
        source, path, transmitter, receiver = key
        used                                = variables.arc_used[key]
        packets                             = variables.path_packets[(source, path)]
        suffix                              = f"k{source}_l{path}_i{transmitter}_j{receiver}"

        problem += (flow - big_m * (1 - used) <= packets, f"c15_phantom_upper_{suffix}")
        problem += (flow + big_m * (1 - used) >= packets, f"c16_phantom_lower_{suffix}")


"""
    Paper: Section III-C, Constraint (17).
    
    Any used directed data link also generates control traffic on that indexed directed 
    control variable (accounting for bidirectional use).
"""
def _add_constraint_17_control_flow(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    control_packets = (
        env.experiment.control_to_data_frequency * env.paper.network.number_of_rounds
    )

    if not float(control_packets).is_integer() :
        raise ValueError("xi*N_r must be integral because g is an integer variable")

    for key, control_flow in variables.control_flow.items() :
        source, path, transmitter, receiver = key
        reverse_key                         = (source, path, receiver, transmitter)

        ## NOTE: ASK ABOUT IT
        if reverse_key not in variables.arc_used :
            raise ValueError("Constraint (17) requires a reverse directed arc")

        problem += (
            control_flow
            == control_packets
            * (variables.arc_used[key] + variables.arc_used[reverse_key]),
            f"c17_control_k{source}_l{path}_i{transmitter}_j{receiver}",
        )


"""
    Paper: Section III-C, Constraint (18).

    Source k must leave itself on at least κ_k distinct path slots.
"""
def _add_constraint_18_non_uniform_connectivity(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    for source in env.network.sensors :
        outgoing       = _outgoing_arcs(env, source)
        required_paths = env.connectivity.kappa_by_sensor[source]

        problem += (
            pulp.lpSum(
                variables.arc_used[(source, path, *arc)]
                for path in _paths(env)
                for arc in outgoing
            )
            >= required_paths,
            f"c18_kappa_k{source}",
        )


"""
    Paper: Section III-C, Constraints (19)–(20).
    
    Two paths of the same source cannot both traverse the same relay node.
"""
def _add_constraints_19_20_node_disjointness(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    for source in env.network.sensors :
        for relay in env.network.sensors :
            if relay == source :
                continue

            outgoing = _outgoing_arcs(env, relay)
            incoming = _incoming_arcs(env, relay)

            problem += (
                pulp.lpSum(
                    variables.arc_used[(source, path, *arc)]
                    for path in _paths(env)
                    for arc in outgoing
                )
                <= 1,
                f"c19_node_out_i{relay}_k{source}",
            )
            problem += (
                pulp.lpSum(
                    variables.arc_used[(source, path, *arc)]
                    for path in _paths(env)
                    for arc in incoming
                )
                <= 1,
                f"c20_node_in_i{relay}_k{source}",
            )


"""
    Paper: Section III-C, Constraint (21).
    
    For each sensor i, total transmission energy + reception energy ≤ ε.
"""
def _add_constraint_21_energy(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None :
    data_bits        = env.paper.network.data_packet_size_bits
    control_bits     = env.paper.network.control_packet_size_bits
    reception_energy = env.energy.reception_energy_j_per_bit

    for node in env.network.sensors :
        outgoing        = _outgoing_arcs(env, node)
        incoming        = _incoming_arcs(env, node)
        transmit_energy = pulp.lpSum(
            env.energy.link_transmission_energy_j_per_bit[arc]
            * (
                variables.data_flow[(source, path, *arc)] * data_bits
                + variables.control_flow[(source, path, *arc)] * control_bits
            )
            for source in env.network.sensors
            for path in _paths(env)
            for arc in outgoing
        )
        receive_energy = pulp.lpSum(
            reception_energy
            * (
                variables.data_flow[(source, path, *arc)] * data_bits
                + variables.control_flow[(source, path, *arc)] * control_bits
            )
            for source in env.network.sensors
            for path in _paths(env)
            for arc in incoming
        )

        problem += (
            transmit_energy + receive_energy <= variables.maximum_sensor_energy,
            f"c21_energy_i{node}",
        )


"""
    Paper: Section III-C, Constraint (22), using Eq. (26).

    Interference model.

    The paper writes the interference-link domain as ``A\\{i}``. We interpret
    this as links not incident to node ``i`` because its own transmission and
    reception airtime are already represented by the first two terms.
"""
def _add_constraint_22_bandwidth(
    problem     : pulp.LpProblem,
    variables   : ModelVars,
    env         : EnvironmentData,
) -> None:
    data_bits       = env.paper.network.data_packet_size_bits
    control_bits    = env.paper.network.control_packet_size_bits
    data_rate       = env.paper.network.data_rate_bps
    available_time  = (
        env.paper.network.number_of_rounds * env.paper.network.round_duration_s
    )

    for node in env.network.nodes:
        outgoing    = _outgoing_arcs(env, node)
        incoming    = _incoming_arcs(env, node)
        interfering = tuple(
            arc
            for arc in env.interference.interfering_arcs_by_node[node]
            if node not in arc
        )

        own_transmit_time = pulp.lpSum(
            (
                variables.data_flow[(source, path, *arc)] * data_bits
                + variables.control_flow[(source, path, *arc)] * control_bits
            )
            / data_rate
            for source in env.network.sensors
            for path in _paths(env)
            for arc in outgoing
        )

        own_receive_time = pulp.lpSum(
            (
                variables.data_flow[(source, path, *arc)] * data_bits
                + variables.control_flow[(source, path, *arc)] * control_bits
            )
            / data_rate
            for source in env.network.sensors
            for path in _paths(env)
            for arc in incoming
        )

        blocked_time = pulp.lpSum(
            (
                variables.data_flow[(source, path, *arc)] * data_bits
                + variables.control_flow[(source, path, *arc)] * control_bits
            )
            / data_rate
            for source in env.network.sensors
            for path in _paths(env)
            for arc in interfering
        )

        problem += (
            own_transmit_time + own_receive_time + blocked_time <= available_time,
            f"c22_bandwidth_i{node}",
        )
